### ISSUE TITLE
Hackothon todo list

### ISSUE THREAD

**Issue by dmcdougall** [libantioch/antioch#223]
- [ ] 1. More unit testing of �KineticsTheory� transport. As mentioned above, I was getting erroneous results with the Ozone flame with kinetics theory transport (IIRC, this manifest as temperature going unstable near where the reaction was starting). Also compare against Cantera output.
- [ ] 2. Move existing �standalone� unit tests to CppUnit-based tests.
- [ ] 3. Split out vibrational and electronic input into their own input files (for ASCII format).
- [ ] 4. Add vibrational/electronic species data parsing to XML format. Make sure there�s no cross-compatibility issues with Cantera.
- [ ] 5. Abandon parsing species molar mass and use elemental molar masses to sum up into species molar mass. This is what Cantera does and what we should be doing to more easily enable more complex species.
- [ ] 6. Add examples directory and example programs for usage. Kinetics, thermo, transport.
- [ ] 7. Add github.io website for Antioch and publish Doxygen documentation.
- [ ] 8. Get CI testing going on UB servers if Civet is open-sourced between now and then.
- [ ] 9. Populate more Blottner data based on fits to data (either the data roystgnr used the other day or, if we have confidence in our KineticsTheory implementation, use that).
